version: "3.8"

services:
  verity-ai:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "6000:6000"
    environment:
      - MODEL_PATH=/app/model.joblib
      - PORT=6000
      - FLASK_DEBUG=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - ../.env  # Optional: if you have a .env file in the root directory
    volumes:
      # Optional: Mount logs directory for debugging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
