apiVersion: v1
kind: ConfigMap
metadata:
  name: verity-ai-config
  namespace: default
data:
  MODEL_PATH: "/app/model.joblib"
  PORT: "6000"
  FLASK_DEBUG: "false"
  GUNICORN_WORKERS: "2"
  GUNICORN_TIMEOUT: "120"